### ISSUE TITLE
about the training way

### ISSUE THREAD

**Issue by diadestiny** [jinyeying/nighttime_dehaze#3]
Hello, may I know if your network was trained using an unpaired or paired approach? In your paper, you mentioned that your network was trained based on a CycleGAN-based network (an unpaired training method). However, in the experimental section, you stated that a paired GTA5 dataset was used for training.

**Comment by jinyeying** [comment]
> Hello, may I know if your network was trained using an unpaired or paired approach? In your paper, you mentioned that your network was trained based on a CycleGAN-based network (an unpaired training method). However, in the experimental section, you stated that a paired GTA5 dataset was used for training.

Hi, it is semi-supervised. For the real images do not have ground truth, it is unsupervised. As for the paired GTA5 dataset, it is supervised. The whole method is semi-supervised.
