### ISSUE TITLE
Test Result

### ISSUE THREAD

**Issue by weiMytian** [jinyeying/nighttime_dehaze#4]
![1702610376861](https://github.com/jinyeying/nighttime_dehaze/assets/91456825/e2f62b94-11e5-4ec8-a15f-7c34b324e52e)
The visual effect deviation obtained from the test weight you provided is significant. Is the weight file you provided the final weight file used in your paper?

**Comment by jinyeying** [comment]
> ![1702610376861](https://private-user-images.githubusercontent.com/91456825/290715684-e2f62b94-11e5-4ec8-a15f-7c34b324e52e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDY0MTMsIm5iZiI6MTcwMjgwNjExMywicGF0aCI6Ii85MTQ1NjgyNS8yOTA3MTU2ODQtZTJmNjJiOTQtMTFlNS00ZWM4LWExNWYtN2MzNGIzMjRlNTJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA5NDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGZiNzZhMzVmZTA2NWE2N2QxZjIzYWNiNjQwYTA5NzY5ODFlYzBlYjQ1OGI5N2QyNTdhMTFmMmRkZmMwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tf6Y7XYmEJpGtAaGaXq8ov-rCqE1kaOQsLBixlm7GDY) The visual effect deviation obtained from the test weight you provided is significant. Is the weight file you provided the final weight file used in your paper?

I added a post-process to enhance the visual results. It is a Matlab code and I will clean it.

**Comment by jinyeying** [comment]
> > ![1702610376861](https://private-user-images.githubusercontent.com/91456825/290715684-e2f62b94-11e5-4ec8-a15f-7c34b324e52e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDY0MTMsIm5iZiI6MTcwMjgwNjExMywicGF0aCI6Ii85MTQ1NjgyNS8yOTA3MTU2ODQtZTJmNjJiOTQtMTFlNS00ZWM4LWExNWYtN2MzNGIzMjRlNTJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA5NDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGZiNzZhMzVmZTA2NWE2N2QxZjIzYWNiNjQwYTA5NzY5ODFlYzBlYjQ1OGI5N2QyNTdhMTFmMmRkZmMwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tf6Y7XYmEJpGtAaGaXq8ov-rCqE1kaOQsLBixlm7GDY) The visual effect deviation obtained from the test weight you provided is significant. Is the weight file you provided the final weight file used in your paper?
> 
> I added a post-process to enhance the visual results. It is a Matlab code and I will clean it.

Maybe can try the post-process Matlab code in https://github.com/jinyeying/nighttime_dehaze/tree/main/ENHANCEMENT.
