### ISSUE TITLE
light Source matting

### ISSUE THREAD

**Issue by heyuwen123** [jinyeying/nighttime_dehaze#6]
Hello, the light source mask in your article uses alpha matting. Do you manually add scribbles to each light source mask?

**Comment by jinyeying** [comment]
> Hello, the light source mask in your article uses alpha matting. Do you manually add scribbles to each light source mask?

No, in the code, it is 
text_map_refined2 = ff(text_map_refined*255)/255;
https://github.com/jinyeying/nighttime_dehaze/blob/1de8ba441f1512f1c7dd92971c59fe2f8241e64d/APSF_GLOW_RENDER_CODE/synthetic_glow_pairs.m#L41

alpha matting可以读一下L37-L41的代码，参考的A Contrast Enhancement Framework with JPEG Artifacts Suppression，ECCV2014的工作。

light source mask简单粗暴的用intensity大，也就是亮的地方得到的。https://github.com/jinyeying/nighttime_dehaze/blob/1de8ba441f1512f1c7dd92971c59fe2f8241e64d/APSF_GLOW_RENDER_CODE/synthetic_glow_pairs.m#L34

**Comment by heyuwen123** [comment]
非常感谢！
