### ISSUE TITLE
Could you please tell me what the parameters and calculations of the network are?

### ISSUE THREAD

**Issue by Wing100** [jinyeying/nighttime_dehaze#7]

**Comment by Wing100** [comment]
What are the parameters and flops of the network?

**Comment by Wing100** [comment]
Among the results of the NHR data set, which one of img_01 and img_02 is your experimental result?

**Comment by jinyeying** [comment]
> What are the parameters and flops of the network?

I have released the checkpoint, see "Download the checkpoint [dehaze.pt](https://www.dropbox.com/scl/fi/y634lpwli4u8dosn0o28r/dehaze.pt?rlkey=lmz1yjlga39somlfr6s0618q8&dl=0)"

**Comment by jinyeying** [comment]
> Among the results of the NHR data set, which one of img_01 and img_02 is your experimental result?

https://github.com/jinyeying/nighttime_dehaze/blob/1de8ba441f1512f1c7dd92971c59fe2f8241e64d/results/NHR/output/0006.jpg
