### ISSUE TITLE
How to get these parameters?

### ISSUE THREAD

**Issue by kaka45inablink** [jinyeying/nighttime_dehaze#8]
https://github.com/jinyeying/nighttime_dehaze/blob/4ef0186600304acdebf4f9aa42b2f9461a54c293/APSF_GLOW_RENDER_CODE/synthetic_glow_fig3_visualization.m#L33-L37

Hi, dear author,
Can you explain how to get these parameters?

**Comment by jinyeying** [comment]
> https://github.com/jinyeying/nighttime_dehaze/blob/4ef0186600304acdebf4f9aa42b2f9461a54c293/APSF_GLOW_RENDER_CODE/synthetic_glow_fig3_visualization.m#L33-L37
> 
> Hi, dear author, Can you explain how to get these parameters?

![image](https://github.com/jinyeying/nighttime_dehaze/assets/36725804/97832a58-f006-4cb4-998f-8b6f67849f04)

The quadratic equation for the param was derived through curve fitting and empirical tuning.
