### ISSUE TITLE
Could you please share me your training code?

### ISSUE THREAD

**Issue by unlikehuman** [jinyeying/nighttime_dehaze#9]
I used your test code to do an inference on the RTX4090D and calculated FPS=2.45.On this basis, I want to use the pruning algorithm to perform unstructured pruning of the network to improve the efficiency of model inference.Could you please share your training code to my email 1609596836@qq.com ?Anyway, thanks a lot for your code.

**Comment by jinyeying** [comment]
> I used your test code to do an inference on the RTX4090D and calculated FPS=2.45.On this basis, I want to use the pruning algorithm to perform unstructured pruning of the network to improve the efficiency of model inference.Could you please share your training code to my email [1609596836@qq.com](mailto:1609596836@qq.com) ?Anyway, thanks a lot for your code.

Hi, the training code has been modified on [U-GAT-IT](https://github.com/znxlwm/UGATIT-pytorch). One trick used in networks.py is to change out = self.UpBlock2(x) to [out = (self.UpBlock2(x)+input).tanh()](https://github.com/jinyeying/DC-ShadowNet-Hard-and-Soft-Shadow-Removal/blob/35aaf00625f039f9f331d261355945c5eb1a8806/networks.py#L103) to learn a residual. The full version I have not cleaned yet.
